site_name: 类脑宝宝教程
site_url: https://down-3ud.pages.dev
nav: 
  - "首页":
    - index.md
  - "搭建部署":
    - "首页": build/index.md
    - "Windows本地部署酒馆与clewd教程": build/silly.md
    - "通过 Github Desktop 在PC本地安装酒馆/Clewd/YouChat_Proxy": build/gitdesk.md
    - "VPS 云端部署酒馆与Clewd": build/vps.md
    - "傻瓜式图文教程:SillyTavern Docker 一键部署教程,开箱即用的容器版酒馆！": build/dock.md
  - "酒馆使用": 
    - "首页": silly/index.md
    - "酒馆介绍——萌新向": silly/tavern.md
    - "VPS酒馆更新": silly/up.md
    - "正确导入/导出更新后角色卡的方法": silly/char.md
    - "前端卡问题自查教程": silly/css.md
  - "获取ai渠道": 
    - "首页": get_ai/index.md
    - "Clewd报错大全": get_ai/clewd.md
    - "Pro退款流教程": get_ai/pro_refund.md
theme: 
  name: material
  language: zh
  plugins:
    - search
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.indexes
    - search.suggest
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette: 

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preferenceocs/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
